CREATE TABLE produtos(
    id BIGINT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(75) NOT NULL,
    descricao VARCHAR(150) NOT NULL,
    preco DECIMAL(10, 2) NOT NULL,
    ativo TINYINT NOT NULL,
    PRIMARY KEY(id)
);
